### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR on http://pgrok.dev

### ISSUE THREAD

**Issue by menduo** [pgrok/pgrok#24]
### Version

1

### Describe the bug

http://pgrok.dev/ is unreachable because ERR_SSL_PROTOCOL_ERROR

### To reproduce

1. Goto https://github.com/pgrok/pgrok#set-up-the-client-pgrok
2. Click http://pgrok.dev/ in "Go to http://pgrok.dev/"
3. Get warning from the browser 

### Expected behavior

1. Reachable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
There is no such site :)
