### ISSUE TITLE
docker: build images in CI and provide `docker-compose.yml`

### ISSUE THREAD

**Issue by unknwon** [pgrok/pgrok#27]
## TODO

- [x] Build images in CI
- [x] Provide `docker-compose.yml`, includes `pgrokd`, `postgresql` and `caddy`
- [x] User documentation

**Comment by mosamlife** [comment]
@unknwon  we can add caddy image also for seamless integration.

**Comment by unknwon** [comment]
> @unknwon we can add caddy image also for seamless integration.

Good idea, I will take a note.

**Comment by unknwon** [comment]
I did not add caddy just for a hypothetic use case unless there is a production setup that wants exactly that.
