### ISSUE TITLE
config does not support pathing

### ISSUE THREAD

**Issue by gedw99** [pgrok/pgrok#41]
Nitpicking i know.. 

``` 
pgrok --config $(PWD)/pgrok.example.yml does not work
pgrok --config pgrok.example.yml does not work

2023-03-30 11:40:05 FATA Failed to load config config=/Users/apple/.pgrok/pgrok.yml error="read file: open /Users/apple/.pgrok/pgrok.yml: no such file or directory"

```

Would be nice if the --config arg did allow overriding

---

Also pgrokd -config pgrokd.exmaple.yml uses a different arg syntax. Would be nice if we used "--" for all config args ?

Also fix the spelling of "exmaple"...

### Consent

- [X] I agree to follow the [Code of Conduct](https://go.dev/conduct)
- [X] I understand a satisfying answer is not guaranteed

**Comment by gedw99** [comment]
yes i think thats the nature of the problem.  I need to go back into my test code though and check.

Can i ask something related ? It would be good is Postgresql was optional. Makes it much quicker to work without the extra complexity.  I know that's more work though, so was wondering  is there a way to run the code in a basic form without the need for Postgresql ?

**Comment by unknwon** [comment]
> Can i ask something related ? It would be good is Postgresql was optional. Makes it much quicker to work without the extra complexity. I know that's more work though, so was wondering is there a way to run the code in a basic form without the need for Postgresql ?

I think the main point of using this tool is to have the concept of principals with SSO and thus stable URLs. So I guess it loses point in a "basic form" (whatever it means).

Is it because the external PostgreSQL requirement? Adding SQLite support is the most obvious choice but my deployments use PostgreSQL so I'd have to add bunch of DB integration tests to make sure other types of DB continues to work (as part of the support work).

**Comment by gedw99** [comment]
I still need to work on the issue, so will swing back to this.

its ok, am using cockroach with it without docker.     I might add a simple ETC db later if your interested.

**Comment by unknwon** [comment]
> I might add a simple ETC db later if your interested.

😁 What is a "ETC db later"?

**Comment by gedw99** [comment]
sorry,  mean ETCD server.

I saw how simpe the sql is and so its easier to use a simple store with basic search maybe.
