### ISSUE TITLE
Stable ports for TCP tunnels

### ISSUE THREAD

**Issue by anonsaber** [pgrok/pgrok#43]
### Type out the question

For tcp tunnels,  how to specify the port of the server?

### Consent

- [X] I agree to follow the [Code of Conduct](https://go.dev/conduct)
- [X] I understand a satisfying answer is not guaranteed

**Comment by XiaFanGit** [comment]
@unknwon Sure, for example, ngrok offers a feature in its paid version that allows you to use a fixed port.

**Comment by unknwon** [comment]
Semi-stable TCP port assignment is supported in https://github.com/pgrok/pgrok/pull/49.
