### ISSUE TITLE
will this setup only work with https and not http

### ISSUE THREAD

**Issue by mehulgithub-1903** [pgrok/pgrok#59]
### Type out the question

I am using a HTTP domain which then is unable to set the reverse proxy through caddy doing this i am facing a error.

### Consent

- [X] I agree to follow the [Code of Conduct](https://go.dev/conduct)
- [X] I understand a satisfying answer is not guaranteed

**Comment by unknwon** [comment]
Hi, as the README states, HTTPS is _not_ required. If you encounter errors on the Caddy side, you'd need to post the errors. Otherwise there is no way to help you :)

**Comment by mehulgithub-1903** [comment]
will this work with nginx instead of caddy

**Comment by unknwon** [comment]
I haven't used NGINX ever-since Caddy came out, this is what AI says 😂 

<img width="593" alt="CleanShot 2023-06-09 at 19 13 51@2x" src="https://github.com/pgrok/pgrok/assets/2946214/fbba5d3e-46f7-43e1-aea8-fef081995360">

```nginx
server {
    listen 80;
    server_name ~^(?<subdomain>.+)\.example\.com$;
    location / {
        proxy_pass http://backend-$subdomain.example.com;
    }
}
```
