### ISSUE TITLE
docs: HTTPS example setup

### ISSUE THREAD

**Issue by mehulgithub-1903** [pgrok/pgrok#66]
### Type out the question

what all changes needs to be done to make the setup https

### Consent

- [X] I agree to follow the [Code of Conduct](https://go.dev/conduct)
- [X] I understand a satisfying answer is not guaranteed

**Comment by unknwon** [comment]
I wrote up a guide in https://github.com/pgrok/pgrok/blob/main/docs/admin/https.md, please let me know if that helps!
