### ISSUE TITLE
[Question] - it possible to spin up pgrok without an authentication provider?

### ISSUE THREAD

**Issue by dinbtechit** [pgrok/pgrok#69]
### Type out the question

it possible to spin up pgrok without an authentication provider?

### Consent

- [X] I agree to follow the [Code of Conduct](https://go.dev/conduct)
- [X] I understand a satisfying answer is not guaranteed

**Comment by unknwon** [comment]
Hey @dinbtechit!

It is not possible in its current form, since the SSO is kinda part of the purpose why this project exists for solving the original problem.

May I ask what is your use case?

**Comment by dinbtechit** [comment]
Hi @unknwon! Thank you your reply I was looking for something easy to deploy in my Orange Pi. Having setup an authentication provider seems like a lot of effort. Maybe I'll just follow your guide. Thanks for an awesome project.!!

**Comment by unknwon** [comment]
BTW GitLab.com is OIDC-compatible, so if you just want something works with OIDC that could be used (but of course... all gitlab.com might be able to login your pgrokd web UI, unless you have a unique email domain that could be used to enforce).
